"""empty message

Revision ID: 314368595409
Revises: 52fc59c0aae1
Create Date: 2021-03-17 01:51:45.519470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314368595409'
down_revision = '52fc59c0aae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_direction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('Faculty', 'faculty', ['faculty_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_direction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculty_id')

    # ### end Alembic commands ###
