"""empty message

Revision ID: 440b4643485b
Revises: 6c3b67c2a2ec
Create Date: 2021-03-17 21:30:47.018635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440b4643485b'
down_revision = '6c3b67c2a2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dean_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('Dean', 'dean', ['dean_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dean_id')

    # ### end Alembic commands ###
