"""empty message

Revision ID: 6768b296c2e9
Revises: fa6586e3e9d7
Create Date: 2021-03-19 06:45:27.922155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6768b296c2e9'
down_revision = 'fa6586e3e9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('Subject', 'teacher', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('Subject', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
