"""empty message

Revision ID: 6ab30f4ca0e2
Revises: 
Create Date: 2021-03-16 14:57:15.408955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab30f4ca0e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollee', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
