"""empty message

Revision ID: 78dcb3bdd458
Revises: 440b4643485b
Create Date: 2021-03-17 21:39:58.609267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dcb3bdd458'
down_revision = '440b4643485b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dean', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('post', sa.String(length=90), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dean', schema=None) as batch_op:
        batch_op.drop_column('post')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
