"""empty message

Revision ID: 996c287fb546
Revises: a62f75357f1e
Create Date: 2021-03-19 04:06:01.570324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996c287fb546'
down_revision = 'a62f75357f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
