"""empty message

Revision ID: 9c6b90c2364f
Revises: 6ab30f4ca0e2
Create Date: 2021-03-16 20:47:37.968174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6b90c2364f'
down_revision = '6ab30f4ca0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consideration_stage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollee', schema=None) as batch_op:
        batch_op.drop_column('consideration_stage')

    # ### end Alembic commands ###
