"""empty message

Revision ID: a62f75357f1e
Revises: fa0fe705d679
Create Date: 2021-03-19 04:02:47.215792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62f75357f1e'
down_revision = 'fa0fe705d679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('Teacher', 'teacher', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('Teacher', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
