"""empty message

Revision ID: ab61a316eb87
Revises: 
Create Date: 2021-03-18 06:07:11.428859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab61a316eb87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('groups', 'students_group', ['student_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('groups', type_='foreignkey')
        batch_op.drop_column('student_group_id')

    # ### end Alembic commands ###
