"""empty message

Revision ID: cd8d9c1b543a
Revises: 01a9c0651b85
Create Date: 2021-03-17 19:37:49.220257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8d9c1b543a'
down_revision = '01a9c0651b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residence_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passport', schema=None) as batch_op:
        batch_op.drop_column('residence_address')

    # ### end Alembic commands ###
