"""empty message

Revision ID: e3274a26968b
Revises: 996c287fb546
Create Date: 2021-03-19 05:13:19.051593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3274a26968b'
down_revision = '996c287fb546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('students_group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('students_group_id', sa.INTEGER(), nullable=True))
        # batch_op.create_foreign_key(None, 'students_group', ['students_group_id'], ['id'])

    # ### end Alembic commands ###
